### Geta list of all products
GET http://localhost:3000/products

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "iPhone 11 Pro Max",
    "price": 1199
}

### Get a product by id
GET http://localhost:3000/products/5f304bd649a0bd1b3054072

### Update a product by id
PATCH http://localhost:3000/products/5f304c3249a0bd1b30540722
Content-Type: application/json

{
    "name" : "iPhone 11 Pro",
    "price" : 899
}

### Delete a product by id
DELETE http://localhost:3000/products/5f304dbfa6b7471b904de41f

### Other
GET http://localhost:3000/user/1